### ISSUE TITLE
Master Changelog is incomplete

### ISSUE THREAD

**Issue by svarlitskiy** [glennrp/libpng#115]
[CHANGES.txt](https://github.com/glennrp/libpng/files/318237/CHANGES.txt)

The CHANGES file on the master branch is missing changes from previous revisions. For Example, the last 20 or so changes for each of the libpng15, libpng14, libpng12, and libpng10 are missing in the master file. Shouldn't they all be there?

I've attached a corrected version of the CHANGES file with all the version listed in sequence.

**Comment by jbowler** [comment]
I think the master branch is a collapsed tree, so even though the changes from 1.5.8 to 1.5.14 appear as earlier commits in the master branch they were discarded when libpng 1.6.0 was committed, therefore they should not appear in the change log, any more than the changes from 1.5.15 to 1.5.27 (the current 1.5 release) should.

**Comment by glennrp** [comment]
The changes from 1.5.8 to 1.5.14 appear in CHANGES because at that time libpng15 was the master (pbulic) branch.  Most if not all of those changes also appear under libpng-1.6.0beta/rc entries.  libpng16 became the master on February 14, 2013.  Adding those, and the libpng17 changes, would just make things confusing and inaccurate.

**Comment by glennrp** [comment]
Won't fix.
