### ISSUE TITLE
Potential memory leak in png_handle_pCAL.

### ISSUE THREAD

**Issue by dj2** [glennrp/libpng#133]
Given a correctly crafted PNG it is possible that the params passed into `png_set_pCAL` will fail the if `(params[i] == NULL ||  !png_check_fp_string(params[i], strlen(params[i])))` check. If that happens then a `longjmp` will occur to some other location in the code.

This causes the `params` pointer allocated in `png_handle_pCAL` to leak.

I have a potential fix in: https://codereview.chromium.org/2292313003/ which I can turn into a pull request if its the correct approach to fixing the issue.

**Comment by glennrp** [comment]
Thanks; it looks OK to me.   This didn't make it into libpng-1l6.25 which I
released today, so it''ll have to go into the next beta.  You can submit a
pull request if you like, but I could just use the referenced patch.

Glenn

**Comment by dj2** [comment]
Feel free to grab the patch, otherwise I can put up the pull request on Monday or Tuesday.

**Comment by jbowler** [comment]
It's an API, the caller has to do any required clean-up.  Historically png_handle_<chunk> has checked the parameters so that png_set_<chunk> does not error out, this design is of course totally bogus but it is what it is (I'm working on a new design for 1.7, but it is a major rewrite.)

The rule of thumb is that png_handle_<chunk> has to stash all the memory it allocates in png_struct before calling png_set_<chunk> and png_handle_pCAL is violating this and allocating memory unnecessarily; it can (and should) stack allocate 'params'.

BTW, even if it wasn't an API a called function should never de-allocate data allocated  in the caller, at least not in C.

**Comment by jbowler** [comment]
IRC the same issue was found with sPLT (which is a core chunk, not an extension) and this lead to 'png_chunk_report' which does the right thing.  In the past png_set_<chunk> was written to call png_warning after the first memory allocation (i.e. inside png_set_<chunk>) so error handling was somewhat weird.  png_chunk_benign_error does not work in png_set_<chunk> both because it is not a benign error in write and because, IRC, it doesn't actually build if PNG_NO_READ.

I'm testing a patch that should fix it correctly, without the need to stack-allocate.  I've reviewed pngrutil.c; this seems to be the only case left of this bug (though it is very easy to introduce new instances; after all this one was introduced by adding the check on the parameter format in pngset.c without duplicating it in pngrutil.c (all the other checks are repeated in png_handle_pCAL!)

**Comment by glennrp** [comment]
John's patch has been applied to the head of the libpng16 branch of glennrp/libpng; see https://github.com/glennrp/libpng/pull/135
