### ISSUE TITLE
Cocoapods support

### ISSUE THREAD

**Issue by cuva** [glennrp/libpng#273]
Hi,

It looks like a podspec [has been submitted to cocoapods](https://cocoapods.org/pods/libpng) to make it easily integrable in Objective-C / Swift.

Unfortunately it seems the podspec wasn't committed to this repo and there's an [issue when building for arm devices](#219).

I'd like to submit either a new podspec or update the existing podspec to make it work for arm devices and then push it to the trunk.

Would you be ok to accept a PR that adds a single `.podspec` file to this repo?

/cc @Interfere who I believe wrote the original podspec.

**Comment by ctruta** [comment]
There are, already, too many build systems for libpng. Testing and maintenance efforts, including the continuous integration efforts, are quite a challenge, and opening the floodgates to non-C build systems would be a very bad idea in the long run.

In my opinion, the dedicated cocoapods repo is better suited for this kind of work.

As for the issues with building on the ARM devices, they should all be fixed in the main repo, with all of the existing build systems.
