### ISSUE TITLE
Setjmp/longjmp issues

### ISSUE THREAD

**Issue by amberbhardwaj** [glennrp/libpng#324]
I follow the instruction given in the INSTALL to disable setjmp() and longjmp() function which is mentioned below in INSTALL file:
     **XVI. Setjmp/longjmp issues**

So whenever we pass a non-png file to read through PNG API, in that case, it's calling both the functions for which I already added a macro based on following the instruction described in INSTALL:

**you should
configure libpng with PNG_NO_SETJMP in your pngusr.dfa file, with
-DPNG_NO_SETJMP on your compile line, or with

    #undef PNG_SETJMP_SUPPORTED

in your pnglibconf.h or pngusr.h.**

And my code is still throwing an error related to 
**The value of ESP was not properly saved across a function call. This is usually a result of calling a function declared with one calling convention with a function pointer declared with a different calling convention.** 

Note: _I am using multiple threads and working on the thread-safe platform._

**Comment by ctruta** [comment]
If you disable setjmp/longjmp, you will be relying exclusively on the default error handler, whose behavior is to print an error to STDERR and `abort()` immediately. See `png_default_error()`.

What you need to do here is implement your own error handler and pass it as `user_error_ptr` in either `png_create_read_struct()` or `png_create_write_struct()`. There is sample code that shows you how to do that.

For example, you can implement your own error handler in which you `throw` and exception if you use C++. The important thing here is that you must do something exceptional and interrupt the execution, because `png_error()` used inside the libpng code is about an unrecoverable error. If you don't bail out yourself somehow, it will fall back to its default behavior, which is `abort()`.

As to your last question, about using a different calling convention: I don't know how to help with that without having more specifics. You should be using the "C" `CDECL` calling convention, and not mess with that.

**Comment by amberbhardwaj** [comment]
Thanks for your explanation. As of now, we use with set jump & long jump but I will try the way you suggested to me to avoid this.
