### ISSUE TITLE
Future of libpng

### ISSUE THREAD

**Issue by Thomas1664** [glennrp/libpng#410]
What is the future of libpng and who is the maintainer since @glennrp died?
There are a few issues out there that report memory leaks and there may be other unknown security bugs in the code. Since libpng is used in many popular software products it is critical that there is an active maintainer. 

What about @ctruta?
CC: @danoli3, @LeonScroggins

**Comment by ProgramMax** [comment]
I understand your question is about maintaining the library.

But since you're talking about the future of libpng I figured it is relevant to mention that the PNG standard itself is being updated right now. You can see https://github.com/w3c/PNG-spec and https://www.w3.org/groups/wg/png for details.

We have a roadmap to get spec wording solid and then create Web Platform Tests and libpng pull requests for the changes.

**Comment by thealberto** [comment]
Hi @ProgramMax,
any additional comment on this issue? I haven't seen any movement around `libpng` unfortunately :(

**Comment by ctruta** [comment]
Hello, everyone. Life kept me away from this project for a while... but I'm back :-)
I am happy to close this bug.

**Comment by ProgramMax** [comment]
Glad to have you back, @ctruta. :)
