### ISSUE TITLE
reject a possible valid png file

### ISSUE THREAD

**Issue by boofish** [glennrp/libpng#465]
Hi, I am fuzzing libpng and find a special case: libpng reports `libpng error: s[FF]IT: invalid chunk type` for possible valid png file, because other png parsers (such as libspng, lodepng) accept the file and do not report any error.  
The file is attached :[error.zip](https://github.com/glennrp/libpng/files/10472075/error.zip)

**Comment by nayuki** [comment]
![](https://user-images.githubusercontent.com/672172/215142936-30a8afaf-6c83-4baa-8a78-944783e3d44d.png)

The file is invalid. Chunk types can only use lowercase a-z or uppercase A-Z, as per the spec. 

> Chunk Type | A sequence of four bytes defining the chunk type. Each byte of a chunk type is restricted to the decimal values 65 to 90 and 97 to 122. These correspond to the uppercase and lowercase ISO 646 letters (A-Z and a-z) respectively for convenience in description and examination of PNG datastreams. -- https://www.w3.org/TR/2003/REC-PNG-20031110/#5Chunk-layout

**Comment by LaurentBerger** [comment]
@jbowler 
There is an issue in [opencv](https://github.com/opencv/opencv/issues/23584). Could problem  be an attack?

**Comment by boofish** [comment]
> When I said the "bug" is an attack I meant this bug report. I.e. the report itself is a troll.

I would like to make a clarification that this is not an attack. The report gives evidence and provides poc file, therefore, anyone can reproduce it. Meanwhile, it uses the conservative description with the word `possible valid png`, which calls for further verification from the maintainer. The reason I report this is hoping to improve the quality of the libpng.

**Comment by jbowler** [comment]
> The reason I report this is hoping to improve the quality of the libpng.

You or I can generate literally 1000s of invalid files per second and this is exactly what a fuzzer does.  It is obvious to both of us that libpng is behaving correctly; it is rejecting a manifestly invalid file with an error message.  Did you report it to the other two library maintainers?  More important did you find out why they accept it?

Since you are running a fuzzer, which, by definition, generates invalid data and therefore, by definition, should almost all the time result in an error message from libpng, you need to investigate what is going on BEFORE submitting a bug report.  This isn't specific to libpng, **it is a general comment that applies to any user of a fuzzer**.

For real users who have a file which generates an error, a real file that the user is trying to use in real world scenarios and hasn't obtained by fuzzing, or scraping a damaged disk, the rules are slightly different.  Yet if every user who had a damaged file reported a bug to the upstream library maintainer chaos would result.  This is why the bugs go to the _app maintainers_ (in this case you, since the app is a fuzzer) who then laboriously analyse the file and declare that their app, and by as a result libpng, is behaving correctly.

Most of the time library maintainers who get bugs like this simply resolve them with "not a bug" or, "as intended/designed".   That's why app maintainers don't upstream them without a lot of justification.

**Comment by boofish** [comment]
> Did you report it to the other two library maintainers? 

Not yet, because the other two share the same behavior (i.e., they accepted it), so I reported it here first. I conducted some analysis previously but had trouble locating the root cause, this is why I put here and call for further verification. Even so, I filtered lots of similar cases due to reporting the same error message or another png parser also reporting errors. Meanwhile, I try to provide details as much as possible, e.g., I first claimed that I found it by `fuzzing`, the POC file, etc. What I want to say is that this is not an attack, and it also cost me time to perform an analysis.

> More important did you find out why they accept it?

This is what I need to do next. I appreciate that some discussion from this channel seems helpful

**Comment by jbowler** [comment]
As a general comment for anyone who reads this bug report, **ALWAYS** run `pngcheck -v` on the .png file::

```
$  pngcheck -vvt error.png
File: error.png (138 bytes)
  chunk IHDR at offset 0x0000c, length 13
    7 x 7 image, 2-bit palette, non-interlaced
  chunk gAMA at offset 0x00025, length 4: 1.0000
  invalid chunk name "s�IT" (73 ffffffff 49 54)
ERRORS DETECTED in error.png
```

If `pngcheck` reports any issues and your app is written in such a way that libpng will encounter the same region of the file (e.g. your app doesn't stop the read before getting to the error) then expect libpng to report the same issue as a 'warning' or 'error'.

Note that there are ways to stop libpng reporting errors or warnings and to fine tune exactly what is reported and this can be controlled from the app, many apps don't display warnings and some apps deliberately skip bad chunks (ones with errors) if the chunk isn't required.  Also, in the above case, pngcheck makes no attempt to recover from the error (neither does libpng in this case).

`control/tools/pngfix` can be used to attempt to fix damaged PNG files.  It is necessarily hit-or-miss.  In this case `pngfix `gives the same information in a different way.  No one would claim `pngfix` output is easy to understand!

```
$ pngfix error.png
gAMA ERR 0c read Success Success damaged_PNG_stream error.png
```

Use "pngfix -h" to help decode the output:

>gAMA the chunk (in this case this the damage is in the header of the next chunk so the previous chunk name is output)
>ERR the read was aborted
> **0c** the "_accumulated status code_", a bit field, **4**(_chunk length incorrect_)+**8**(_file truncated_)

As I said, the output can be difficult to decode.  "_od -t x1_" becomes necessary to understand in detail what has happened, but a png chunk dumper which doesn't detect errors might help; the "length" is 3 (see the dump above).  The _file truncated_ report from pngfix is an artefact of aborting the read on the invalid chunk name.

**REMEMBER**: libpng is intended to be an authoritative implementation of the PNG standard.  As such it can be expected to detect errors but it can't (and shouldn't) be expected to fix or ignore them.  Some errors can be ignored in the app, but this isn't one the errors that can be ignored inside libpng.  This error might result in CVE worthy code in other PNG readers (for example if they perfect-hash the chunk name without checking for errors in the name format).

**Comment by boofish** [comment]
> More important did you find out why they accept it?

Hi, @ctruta,  I wanted to provide a minor update. I recently came across the specification of [Error Handling section](https://www.w3.org/TR/png/#13Decoders.Errors) and gained a better understanding of why other two impls accept certain errors.  Specifically, The error occurs with an `ancillary chunk` and the specification states that
> Encountering an unknown ancillary chunk is never an error. The chunk can simply be ignored.

To further illustrate this, I created a PNG image where I modified a single byte of the `sBIT` chunk at offset `0x36` (changing it from `0x42` to `0x01`), without correcting the corresponding CRC. While libpng rejects this image, two other implementations, namely lodepng and libspng, do accept it. 

Considering this observation alongside the specification, it seems that conducting a check to determine whether the chunk is critical before issuing an error would be better.

I hope this information is helpful!

Image attached: ![s32n3p04](https://github.com/glennrp/libpng/assets/52410003/734fc76a-7e4a-4f60-9534-e9c50abf7d53)

**Comment by jbowler** [comment]
No, it's a "transmission error".  Note that libpng conforms to revision 2, the current draft.  The working draft is a work-in-progress (check for the editor's version which changed last on 2023 June 13).  Because it's a transmission error it falls under this clause:

> c) A PNG signature mismatch, a CRC mismatch, or an unexpected end-of-stream indicates a corrupted datastream, and may be regarded as a fatal error. A decoder could try to salvage something from the datastream, but the extent of the damage will not be known.

libpng does not do that; it provides an error to the caller.  Note that the spec as written applies to the "decoder"; libpng isn't a decoder in this context, the decoder is libpng+the calling code (potentially up to the level of the app) and libpng provides enough support to behave in any desired way.

**Comment by boofish** [comment]
thanks for clarification!
