### ISSUE TITLE
build for iOS failed

### ISSUE THREAD

**Issue by leleliu008** [glennrp/libpng#485]
**reported error messages:**

```
CMake Error at CMakeLists.txt:1028 (install):
  install TARGETS given no BUNDLE DESTINATION for MACOSX_BUNDLE executable
  target "pngfix".
```

**used version:**

https://downloads.sourceforge.net/libpng/libpng-1.6.40.tar.xz

**full logs:**

https://github.com/fpliu1214/test/actions/runs/5430226447/jobs/9875895396

**cmake configure command:**

```bash
cat > ios.cmake <<EOF
set(CMAKE_SYSTEM_NAME iOS)
EOF

cmake \
    -Wno-dev \
    -S . \
    -B build.d \
    -DBUILD_TESTING=OFF \
    -DPNG_STATIC=ON \
    -DPNG_SHARED=ON \
    -DPNG_TESTS=OFF \
    -DPNG_DEBUG=OFF \
    -DPNG_ARM_NEON=off \
    -DCMAKE_TOOLCHAIN_FILE=$PWD/ios.cmake
```

**workaround1:**

```bash
gsed -i 's|RUNTIME DESTINATION bin|RUNTIME DESTINATION bin BUNDLE DESTINATION bin|' CMakeLists.txt
```

**workaround2:**

```bash
cat > ios.cmake <<EOF
set(CMAKE_SYSTEM_NAME iOS)
set(CMAKE_MACOSX_BUNDLE OFF)
EOF
```

References:
https://cmake.org/cmake/help/latest/variable/CMAKE_MACOSX_BUNDLE.html
https://github.com/Kitware/CMake/blob/master/Modules/Platform/Darwin.cmake#L1-L4

**Comment by Treata11** [comment]
Hi @leleliu008 
So, were you able to build it for iOS?
I couldn't do it with the instructions you provided.

**Comment by leleliu008** [comment]
look this: https://github.com/leleliu008/xcpkg-package-manually-build/actions/runs/12536426676

**Comment by Treata11** [comment]
> look this: https://github.com/leleliu008/xcpkg-package-manually-build/actions/runs/12536426676

I downloaded it @leleliu008 
But it's not in a `framework` format.

**Comment by leleliu008** [comment]
@Treata11 Yes, I just build it as normal, I didn't bundle it as a framework. bundle it as a framework should not be difficult, right?

**Comment by Treata11** [comment]
> @Treata11 Yes, I just build it as normal, I didn't bundle it as a framework. bundle it as a framework should not be difficult, right?

I manually created an `info.plist` for it (don't know if there's a command to automate bundling)
I noticed there are macOS binaries inside lib dir as well; Thanks for including everything.

**Comment by Treata11** [comment]
The project is already configured with CMake v3.14 
Apple frameworks should be official as explained in:
https://cmake.org/cmake/help/latest/manual/cmake-toolchains.7.html#id27

I wonder, why they still haven't made the necessary changes in the CMake configs of the project itself? So all targets (including simulators) were easily created without relying on scripts.

**Comment by leleliu008** [comment]
this is my formula : https://github.com/leleliu008/xcpkg-formula-repository-official-core/blob/master/formula/libpng.yml

**Comment by leleliu008** [comment]
> don't know if there's a command to automate bundling

I will implement this feature , but I have no time to do it at the moment.

**Comment by Treata11** [comment]
> > don't know if there's a command to automate bundling
> 
> I will implement this feature , but I have no time to do it at the moment.

Thanks again for all the help!

**Comment by leleliu008** [comment]
> I noticed there are macOS binaries inside lib dir as well

They are built for ios, although shared libraries and executables are usually not used for ios developers.

**Comment by Treata11** [comment]
> > I noticed there are macOS binaries inside lib dir as well
> 
> They are built for ios, although shared libraries and executables are usually not used for ios developers.

I used the following to configure:
```bash
$ cmake .. -DCMAKE_SYSTEM_NAME=iOS
```
and this is what I get when I try to build
```bash
$  cmake --build . --config Release --target install
[  0%] Built target png_genfiles
[  1%] Building C object CMakeFiles/png_shared.dir/png.c.o
[  3%] Building C object CMakeFiles/png_shared.dir/pngerror.c.o
...
...
[ 27%] Linking C shared library libpng16.dylib
Undefined symbols for architecture arm64:
  "_png_do_expand_palette_rgb8_neon", referenced from:
      _png_do_expand_palette in pngrtran.c.o
  "_png_do_expand_palette_rgba8_neon", referenced from:
      _png_do_expand_palette in pngrtran.c.o
  "_png_init_filter_functions_neon", referenced from:
      _png_init_filter_functions in pngrutil.c.o
  "_png_riffle_palette_neon", referenced from:
      _png_do_read_transformations in pngrtran.c.o
ld: symbol(s) not found for architecture arm64
cc: error: linker command failed with exit code 1 (use -v to see invocation)
make[2]: *** [libpng16.16.45.git.dylib] Error 1
make[1]: *** [CMakeFiles/png_shared.dir/all] Error 2
make: *** [all] Error 2
```

They haven't setup the `CMAKE_FRAMEWORK` yet...
https://cmake.org/cmake/help/latest/prop_tgt/FRAMEWORK.html

**Comment by jbowler** [comment]
No one is working on it so far as I know; I don't think any of the main developers know enough about iOS or, indeed, Apple's other operating system (the OpenBSD one, MacOS?)  Nevertheless there are substantial changes in libpng 1.8 which move stuff out of the "build system" so that it's just in the source code.  The last failure, which is unrelated to the reported problem, should just not happen with 1.8 simply because all the target-specific files get compiled in all the builds, regardless of the actual target.

So, @Treata11, try libpng-1.8 and raise new issues if it doesn't work.  Note that @leleliu008's original change did try to explicit disable the hardware specific support; there were specific issues on MacOS because of lack of support in cmake for the multilib environment, this is what is fixed in libpng-1.8

Whether any such issues gets fixed depends on having developers who contribute **and maintain** manufacturer specific stuff (e.g. support for build system variants).  Of course if this is a core part of cmake and the approved way of doing things across all platforms then it should happen so long as cmake is supported but there do seem to be quite a few issues along this line (I know next to nothing about cmake).

The original issue was, I believe, itself a bug; neither the command line utilities nor the tests should be built on cross builds because typically an execution environment requires special setup, e.g. in a Docker.  It seems from the libpng-1.8 CMakeLists.txt that this is fixed by the addition of a setting for PNG_TOOLS which is "OFF" for "ANDROID OR IOS).  I have no way of testing this; @leleliu008 can you verify this works, on iOS?  The same fix is in libpng-1.6 so maybe it was made at some time in response to this bug.

There is also an option PNG_TESTS but the default is apparently always ON.  It shouldn't do any harm because the tests shouldn't get executed and it is probably very difficult to build an environment in which to execute them correctly.  This works for me on a hosted amd64 build:

cmake ../CMakeLists.txt -DPNG_TOOLS=OFF -DPNG_TESTS=OFF

@leleliu008 you should find it is not necessary to use the first macro setting (PNG_TOOLS) and the second, which you were setting to OFF, should not harm the build (but it might).  You should also find that disabling the NEON optimizations is no longer necessary in libpng-1.8 and, anyway, PNG_ARM_NEON is no longer supported.

**Comment by Treata11** [comment]
Hi @jbowler 
Thanks for noticing the issue!
I'll take a look at libpng-1.8 branch & see if I can build with tests off.
Might as well be something that I can contribute to!

**Comment by jbowler** [comment]
> Thanks for noticing the issue!

Off topic but the default github setup means that "organisation members"; the "People" here: https://github.com/pnggroup, get an email for when changes occur.  This includes changes to "closed" issues, so there is a point commenting on them at least with the default github setup.  There are also more "People" than the page I quoted will show to you; there are five in this case, but the github default is for organisation members to be "private".

**Comment by Treata11** [comment]
@jbowler 

I tested v1.8 & not only it is macOS compatible, it also builds for an iOS target as well (alongside all other Apple platforms)
These are the two commands that I used:
```bash
cmake -S. -B_builds -GXcode -DPNG_FRAMEWORK=TRUE -DCMAKE_SYSTEM_NAME=iOS 

sudo cmake --build _builds --config Release --target install -- CODE_SIGNING_ALLOWED=NO
```

Almost all the [framework related properties](https://cmake.org/cmake/help/latest/prop_tgt/FRAMEWORK.html#prop_tgt:FRAMEWORK) were already set:

https://github.com/pnggroup/libpng/blob/6184164aa73ee764b1822f44d3db7619cf84f3fa/CMakeLists.txt#L558C1-L567C62



You may have noticed that I've used a new flag `-- CODE_SIGNING_ALLOWED=NO`.
Without it, building wouldn't be possible since a `PRODUCT_BUNDLE_IDENTIFIER` is mandatory. It's just another property that has to be set!
I'll open a PR to fix that if necessary. 
Aside from that, it seems to be complete & thanks again for all the help. I'll shortly include it in an iOS app to see if it actually works.

**Comment by Treata11** [comment]
> Without it, building wouldn't be possible since a `PRODUCT_BUNDLE_IDENTIFIER` is mandatory. It's just another property that has to be set!

I couldn't fix the issue and found out that it's actually an open issue on CMake:
https://gitlab.kitware.com/cmake/cmake/-/issues/24831

**Comment by jbowler** [comment]
Excellent.  Thanks for doing this.  Did you mean a PR for the missing `PRODUCT_BUNDLE_IDENTIFIER`?   That sounds reasonable as `PNG_FRAMEWORK` is explicitly disabled for anything other than `APPLE`.  I'm not sure I understand that bit because the "framework related properties" page doesn't include that.

Anyway, I think a PR would be helpful here since this is a new problem and having a PR with an explanation of what is required (I think just `PRODUCT_BUNDLE_IDENTIFIER `and only then with code signing, which is pretty much a requirement from what I understand).

It seems to me that this might also work against libpng-1.6 so long as `PNG_ARM_NEON=OFF `(this **is** supported in 1.6, if I got the spelling right :-)  Probably best to do it for 1.8 first even so because 1.8 is still in development.
